; Notes:
; priority=1 --> Lower priorities indicate programs that start first and shut down last
; killasgroup=true --> send kill signal to child processes too

; graceful timeout should always be lower than stopwaitsecs to avoid orphan gunicorn workers.
[program:frappe16-bench-frappe-web]
command=/home/sanjayh/frappe16-bench/env/bin/gunicorn -b 127.0.0.1:8001 -w 9 --max-requests 5000 --max-requests-jitter 500 -t 120 --graceful-timeout 30 frappe.app:application --preload
priority=4
autostart=true
autorestart=true
stdout_logfile=/home/sanjayh/frappe16-bench/logs/web.log
stderr_logfile=/home/sanjayh/frappe16-bench/logs/web.error.log
stopwaitsecs=40
killasgroup=true
user=sanjayh
directory=/home/sanjayh/frappe16-bench/sites
startretries=10

[program:frappe16-bench-frappe-schedule]
command=/usr/local/bin/bench schedule
priority=3
autostart=true
stdout_logfile=/home/sanjayh/frappe16-bench/logs/schedule.log
stderr_logfile=/home/sanjayh/frappe16-bench/logs/schedule.error.log
user=sanjayh
directory=/home/sanjayh/frappe16-bench
startretries=10



[program:frappe16-bench-frappe-short-worker]
command=/usr/local/bin/bench worker --queue short,default
priority=4
autostart=true
autorestart=true
stdout_logfile=/home/sanjayh/frappe16-bench/logs/worker.log
stderr_logfile=/home/sanjayh/frappe16-bench/logs/worker.error.log
user=sanjayh
stopwaitsecs=360
directory=/home/sanjayh/frappe16-bench
killasgroup=true
numprocs=1
process_name=%(program_name)s-%(process_num)d
startretries=10

[program:frappe16-bench-frappe-long-worker]
command=/usr/local/bin/bench worker --queue long,default,short
priority=4
autostart=true
autorestart=true
stdout_logfile=/home/sanjayh/frappe16-bench/logs/worker.log
stderr_logfile=/home/sanjayh/frappe16-bench/logs/worker.error.log
user=sanjayh
stopwaitsecs=1560
directory=/home/sanjayh/frappe16-bench
killasgroup=true
numprocs=1
process_name=%(program_name)s-%(process_num)d
startretries=10





[program:frappe16-bench-redis-cache]
command=/usr/bin/redis-server /home/sanjayh/frappe16-bench/config/redis_cache.conf
priority=1
autostart=true
autorestart=true
stdout_logfile=/home/sanjayh/frappe16-bench/logs/redis-cache.log
stderr_logfile=/home/sanjayh/frappe16-bench/logs/redis-cache.error.log
user=sanjayh
directory=/home/sanjayh/frappe16-bench/sites
startretries=10

[program:frappe16-bench-redis-queue]
command=/usr/bin/redis-server /home/sanjayh/frappe16-bench/config/redis_queue.conf
priority=1
autostart=true
autorestart=true
stdout_logfile=/home/sanjayh/frappe16-bench/logs/redis-queue.log
stderr_logfile=/home/sanjayh/frappe16-bench/logs/redis-queue.error.log
user=sanjayh
directory=/home/sanjayh/frappe16-bench/sites
startretries=10



[program:frappe16-bench-node-socketio]
command=/usr/local/bin/bench socketio
priority=4
autostart=true
autorestart=true
stdout_logfile=/home/sanjayh/frappe16-bench/logs/node-socketio.log
stderr_logfile=/home/sanjayh/frappe16-bench/logs/node-socketio.error.log
user=sanjayh
directory=/home/sanjayh/frappe16-bench
startretries=10


[group:frappe16-bench-web]
programs=frappe16-bench-frappe-web,frappe16-bench-node-socketio




[group:frappe16-bench-workers]
programs=frappe16-bench-frappe-schedule,frappe16-bench-frappe-short-worker,frappe16-bench-frappe-long-worker




[group:frappe16-bench-redis]
programs=frappe16-bench-redis-cache,frappe16-bench-redis-queue
